
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eswiv.tela.movimentos;

import br.com.eswiv.auxiliares.DSelecionarObjeto;
import br.com.eswiv.auxiliares.ICalculo;
import br.com.eswiv.dao.DAOBem;
import br.com.eswiv.dao.DAOCalculo;
import br.com.eswiv.modelo.Bem;
import br.com.eswiv.modelo.Bem.Categorias;
import br.com.eswiv.modelo.Calculo;
import br.com.eswiv.modelo.IModelo;
import br.com.eswiv.tela.cadastro.*;
import br.com.eswiv.tela.generico.FrameGenerico;
import br.com.eswiv.tela.principal.DSobreSistema;
import br.com.eswiv.tela.tablemodel.BemTableModel;
import br.com.eswiv.tela.tablemodel.CalculoTableModel;
import com.zap.arca.JASelectPicker;
import com.zap.arca.LoggerEx;
import com.zap.arca.document.NumberValueDocument;
import com.zap.arca.util.WindowUtils;
import java.awt.Component;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.joda.time.DateTime;
import org.joda.time.Months;
import org.joda.time.Years;

/**
 *
 * @author Edidelson
 */
public class FCalculo extends FrameGenerico implements ICalculo {

    private Bem bem;
    private Calculo calculo;
    private CalculoTableModel calculoTableModel = new CalculoTableModel();

    public FCalculo() {
        initComponents();
        setLocationRelativeTo(null);
        iniciar();
        actionMenu(INCLUSAO);
        util.setEnterButton(btOK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        tbIncluir = new javax.swing.JToggleButton();
        tbAlterar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btExcluir = new javax.swing.JToggleButton();
        btPesquisar = new javax.swing.JToggleButton();
        btFiltro = new javax.swing.JToggleButton();
        splitPaneCampos = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCalculo = new com.zap.arca.JATable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plCampos = new javax.swing.JPanel();
        lbValorVenal = new javax.swing.JLabel();
        lbProprietario = new javax.swing.JLabel();
        jsBem = new com.zap.arca.JASelectPicker<Bem>();
        lbDataAquisicao = new javax.swing.JLabel();
        dtAquisicao = new com.zap.arca.JADatePicker();
        lbDescricaoBens = new javax.swing.JLabel();
        tfObervacao = new com.zap.arca.JATextField(100);
        tfCodigo = new com.zap.arca.JATextField(10,0);
        lbCodigo = new javax.swing.JLabel();
        lbBemSelecionado = new javax.swing.JLabel();
        tfValorVenal = new com.zap.arca.JANumberFormatField();
        lbDepreciacao = new javax.swing.JLabel();
        tfDepreciacao = new com.zap.arca.JANumberFormatField();
        jLabel2 = new javax.swing.JLabel();
        tfValorCalculado = new com.zap.arca.JADecimalFormatField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDepreciacaoAcumulada = new com.zap.arca.JADecimalFormatField();
        jButton2 = new javax.swing.JButton();
        btOK = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnIncluir1 = new javax.swing.JMenuItem();
        mnAlterar1 = new javax.swing.JMenuItem();
        mnExcluir1 = new javax.swing.JMenuItem();
        mnLimpar1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAtualizar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnFiltrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cálculo");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonGroup1.add(tbIncluir);
        tbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/add.png"))); // NOI18N
        tbIncluir.setToolTipText("Incluir");
        tbIncluir.setFocusable(false);
        tbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(tbIncluir);

        buttonGroup1.add(tbAlterar);
        tbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/edit.png"))); // NOI18N
        tbAlterar.setToolTipText("Alterar");
        tbAlterar.setFocusable(false);
        tbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbAlterar);
        jToolBar1.add(jSeparator1);

        buttonGroup1.add(btExcluir);
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/delete.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btExcluir);

        buttonGroup1.add(btPesquisar);
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(btPesquisar);

        buttonGroup1.add(btFiltro);
        btFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/filter.png"))); // NOI18N
        btFiltro.setToolTipText("Filtrar");
        btFiltro.setFocusable(false);
        btFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFiltro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltroActionPerformed(evt);
            }
        });
        jToolBar1.add(btFiltro);

        splitPaneCampos.setDividerLocation(120);
        splitPaneCampos.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tbCalculo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbCalculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCalculo);
        tbCalculo.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                alterar(tbCalculo);
            }
        });

        splitPaneCampos.setTopComponent(jScrollPane1);
        splitPaneCampos.setLeftComponent(jScrollPane1);

        jPanel3.setPreferredSize(new java.awt.Dimension(700, 350));

        plCampos.setBackground(new java.awt.Color(255, 255, 255));
        plCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbValorVenal.setText("Valor Venal:");

        lbProprietario.setText("Bem:");

        jsBem.setLabel(lbBemSelecionado);
        jsBem.setName("Bem"); // NOI18N
        jsBem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsBemActionPerformed(evt);
            }
        });
        jsBem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jsBemFocusLost(evt);
            }
        });

        lbDataAquisicao.setText("Data do Cálculo:");

        dtAquisicao.setEnabled(false);
        dtAquisicao.setName("Data do Cálculo"); // NOI18N

        lbDescricaoBens.setText("Observação:");

        tfObervacao.setName("Obervação"); // NOI18N
        tfObervacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfObervacaoActionPerformed(evt);
            }
        });

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        lbCodigo.setText("Código:");

        tfValorVenal.setEnabled(false);
        tfValorVenal.setName("Valor venal"); // NOI18N

        lbDepreciacao.setText("Depreciação:");

        tfDepreciacao.setEnabled(false);
        tfDepreciacao.setName("Depreciação"); // NOI18N

        jLabel2.setText("%");

        tfValorCalculado.setEnabled(false);
        tfValorCalculado.setName("Valor Calculado"); // NOI18N

        jLabel1.setText("Valor Calculado:");

        jLabel3.setText("Depr. Acumulada:");

        tfDepreciacaoAcumulada.setEnabled(false);
        tfDepreciacaoAcumulada.setName("Depreciação Acumulada"); // NOI18N

        javax.swing.GroupLayout plCamposLayout = new javax.swing.GroupLayout(plCampos);
        plCampos.setLayout(plCamposLayout);
        plCamposLayout.setHorizontalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorVenal)
                    .addComponent(lbDescricaoBens)
                    .addComponent(lbProprietario)
                    .addComponent(lbDepreciacao))
                .addGap(27, 27, 27)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfObervacao, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jsBem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbDataAquisicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbBemSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValorVenal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDepreciacao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDepreciacaoAcumulada, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(tfValorCalculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        plCamposLayout.setVerticalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbProprietario)
                        .addGap(13, 13, 13)
                        .addComponent(lbDescricaoBens))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDataAquisicao))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jsBem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbBemSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfObervacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfValorCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfDepreciacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(lbDepreciacao))
                                    .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfDepreciacaoAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))))
                            .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbValorVenal)
                                .addComponent(tfValorVenal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(157, 157, 157))
        );

        jsBem.setDocument(new NumberValueDocument(10));
        tfCodigo.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
            public void changedUpdate(DocumentEvent e) { }
            public void removeUpdate(DocumentEvent e) {
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
        });

        jTabbedPane1.addTab("Cálculo", plCampos);
        plCampos.getAccessibleContext().setAccessibleName("Informações dos Bens");

        jButton2.setText("Cancelar");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btOK, jButton2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOK)
                    .addComponent(jButton2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        splitPaneCampos.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(splitPaneCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(splitPaneCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Editar");

        mnIncluir1.setText("Incluir");
        mnIncluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIncluir1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnIncluir1);

        mnAlterar1.setText("Alterar");
        mnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterar1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnAlterar1);

        mnExcluir1.setText("Excluir");
        mnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExcluir1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnExcluir1);

        mnLimpar1.setText("Limpar");
        mnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLimpar1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnLimpar1);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Exibir");

        mnAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnAtualizar.setText("Atualizar");
        mnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarActionPerformed(evt);
            }
        });
        jMenu3.add(mnAtualizar);
        jMenu3.add(jSeparator2);

        mnFiltrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnFiltrar.setText("Filtrar...");
        mnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFiltrarActionPerformed(evt);
            }
        });
        jMenu3.add(mnFiltrar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenu4.add(jSeparator3);

        mnSobre.setText("Sobre...");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu4.add(mnSobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIncluirActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_tbIncluirActionPerformed

    private void tbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAlterarActionPerformed
        actionMenu(ALTERACAO);
    }//GEN-LAST:event_tbAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        actionMenu(PESQUISAR);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltroActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_btFiltroActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_mnAtualizarActionPerformed

    private void mnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFiltrarActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_mnFiltrarActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        new DSobreSistema(this, true).setVisible(true);
    }//GEN-LAST:event_mnSobreActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        // Verifica se os campos foram preenchidos
        if (verificarCampos(camposVerificar)) {
            // Adiciona ou altera o objeto
            inserirOuAlterar();
            limparCampos();
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfObervacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfObervacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfObervacaoActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void jsBemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsBemActionPerformed
        if (JASelectPicker.SELECT_KEY.equals(evt.getActionCommand())) {
            jsBem.requestFocus();
            new DSelecionarObjeto(this, true, jsBem)
                    .title("Selecionar Bem...")
                    .dao(DAOBem.class)
                    .model(new BemTableModel())
                    .frame(FBem.class)
                    .open();
        }
    }//GEN-LAST:event_jsBemActionPerformed

    private void jsBemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jsBemFocusLost
        if (jsBem.getText().equals("")) {
            lbBemSelecionado.setText("");
            jsBem.setValue(null, "");
            return;
        }
        DAOBem daoBem = new DAOBem();
        String value = jsBem.getEditor().getText();
        Bem c = null;
        if (value.length() > 0) {
            c = daoBem.consultar(Integer.valueOf(value), false);
        }
        jsBem.setValue(c, c != null ? c.getCodigo() : "");
        tfValorVenal.setValue(c != null ? new BigDecimal(c.getValorVenal()) : BigDecimal.ZERO);
        if (jsBem.getValue().getTipo() == Bem.Tipo.USADO) {
            tfDepreciacao.setValue(c != null ? new BigDecimal(c.getDepreciacao() * 2) : BigDecimal.ZERO);
        } else {
            tfDepreciacao.setValue(c != null ? new BigDecimal(c.getDepreciacao()) : BigDecimal.ZERO);
        }
        calcular();
    }//GEN-LAST:event_jsBemFocusLost

    private void mnIncluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIncluir1ActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_mnIncluir1ActionPerformed

    private void mnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterar1ActionPerformed
        actionMenu(ALTERACAO);
    }//GEN-LAST:event_mnAlterar1ActionPerformed

    private void mnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExcluir1ActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_mnExcluir1ActionPerformed

    private void mnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLimpar1ActionPerformed
        actionMenu(LIMPAR);
    }//GEN-LAST:event_mnLimpar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCalculo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btExcluir;
    private javax.swing.JToggleButton btFiltro;
    private javax.swing.JButton btOK;
    private javax.swing.JToggleButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.zap.arca.JADatePicker dtAquisicao;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private com.zap.arca.JASelectPicker<Bem> jsBem;
    private javax.swing.JLabel lbBemSelecionado;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDataAquisicao;
    private javax.swing.JLabel lbDepreciacao;
    private javax.swing.JLabel lbDescricaoBens;
    private javax.swing.JLabel lbProprietario;
    private javax.swing.JLabel lbValorVenal;
    private javax.swing.JMenuItem mnAlterar1;
    private javax.swing.JMenuItem mnAtualizar;
    private javax.swing.JMenuItem mnExcluir1;
    private javax.swing.JMenuItem mnFiltrar;
    private javax.swing.JMenuItem mnIncluir1;
    private javax.swing.JMenuItem mnLimpar1;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JPanel plCampos;
    private javax.swing.JSplitPane splitPaneCampos;
    private javax.swing.JToggleButton tbAlterar;
    private com.zap.arca.JATable tbCalculo;
    private javax.swing.JToggleButton tbIncluir;
    private com.zap.arca.JATextField tfCodigo;
    private com.zap.arca.JANumberFormatField tfDepreciacao;
    private com.zap.arca.JADecimalFormatField tfDepreciacaoAcumulada;
    private com.zap.arca.JATextField tfObervacao;
    private com.zap.arca.JADecimalFormatField tfValorCalculado;
    private com.zap.arca.JANumberFormatField tfValorVenal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciar() {
        dao = new DAOCalculo();

        tbPrincipal = tbCalculo;
        toggleButton = tbIncluir;
        ctChave = tfCodigo;

        tbCalculo.setName("TB_FCALCULO");
        tbCalculo.setModel(calculoTableModel);
        
        camposVerificar = new Component[]{};
        camposLimpar = new Component[]{jsBem, tfValorVenal, tfObervacao, tfDepreciacao,
            jsBem, lbBemSelecionado, tfCodigo, tfDepreciacaoAcumulada, tfValorCalculado};

        WindowUtils.nextEnter(plCampos);
        WindowUtils.exitEsc(this);
        configurarSincronizacao(dao, tbCalculo);
        dtAquisicao.setDate(new java.util.Date());
    }

    @Override
    public void limparCampos() {
        super.limparCampos();
        dtAquisicao.setDate(new java.util.Date());
    }

    
    @Override
    public void inserirOuAlterar() {
        calculo = new Calculo();
        calculo.setAcumulado(tfDepreciacaoAcumulada.getValue());
        calculo.setBem(bem);
        calculo.setValorCalculo(tfValorCalculado.getValue().doubleValue());
        calculo.setDataCalculo(dtAquisicao.getDate());
        calculo.setObservacao(tfObervacao.getText());
        calculo.setAcumulado(tfDepreciacaoAcumulada.getValue());
        try {
            if (tbAlterar.isSelected()) {
                calculo.setCodigo(tfCodigo.intValue());
                dao.alterar(calculo);
            } else {
                dao.adicionar(calculo);
            }
        } catch (RuntimeException e) {
            LoggerEx.log(e);
        }
    }

    @Override
    public void preencherCampos(IModelo m) {
        calculo = (Calculo) m;
        bem = calculo.getBem();
        tfCodigo.setText(String.valueOf(calculo.getCodigo()));
        jsBem.setValue(bem, bem != null ? bem.getCodigo() : "");
        tfDepreciacao.setValue(bem.getDepreciacao().doubleValue());
        tfValorVenal.setValue(bem.getValorVenal().doubleValue());
        tfValorCalculado.setValue(calculo.getValorCalculo().doubleValue());
        dtAquisicao.setDate(calculo.getDataCalculo());
        tfObervacao.setText(calculo.getObservacao());
        DAOCalculo daoCalculo = new DAOCalculo();
        BigDecimal b = daoCalculo.getMaxValue(bem);
        tfDepreciacaoAcumulada.setValue(b);
    }

    public int getPrazoDepreciacao(Bem.Categorias categorias) {
        switch (categorias) {
            case E:
                return Categorias.E.getPrazo();
            case I:
                return Categorias.I.getPrazo();
            case ME:
                return Categorias.ME.getPrazo();
            case MU:
                return Categorias.MU.getPrazo();
            case V:
                return Categorias.V.getPrazo();
            default:
                return 0;
        }
    }

    @Override
    public void preencherTabela(int linha, IModelo i) {
    }

    @Override
    public void calcular() {
        bem = jsBem.getValue();
        if (bem.getTurno() == Bem.Turno.H8 && calcular8Hrs() != null) {
            tfValorCalculado.setValue(calcular8Hrs().doubleValue());
            tfDepreciacaoAcumulada.setValue(calcular8Hrs().doubleValue());
        } else if (bem.getTurno() == Bem.Turno.H16 && calcular16Hrs() != null) {
            tfValorCalculado.setValue(calcular16Hrs().doubleValue());
            tfDepreciacaoAcumulada.setValue(calcular16Hrs().doubleValue());
        } else if (bem.getTurno() == Bem.Turno.H24 && calcular24Hrs() != null) {
            tfValorCalculado.setValue(calcular24Hrs().doubleValue());
            tfDepreciacaoAcumulada.setValue(calcular24Hrs().doubleValue());
        } else {
            if (calcular8Hrs() != null) {
                tfValorCalculado.setValue(calcular8Hrs().doubleValue());
                tfDepreciacaoAcumulada.setValue(calcular8Hrs().doubleValue());
            }
        }
    }

    @Override
    public Double calcular8Hrs() {
        bem = jsBem.getValue();
        BigDecimal percentualDepreciacao = tfDepreciacao.getValue();
        BigDecimal valorCalculado = BigDecimal.ZERO;
        if (bem != null) {
            int meses = getMeses(bem.getAquisicao(), new DateTime(dtAquisicao.getDate()));
            int anos = getAnos(bem.getAquisicao(), new DateTime(dtAquisicao.getDate()));
            double prazo = getPrazoDepreciacao(bem.getGrupo());
            if (bem.getTipo() == Bem.Tipo.USADO) {
                prazo = prazo / 2;
            }
            if (anos > prazo) {
                JOptionPane.showMessageDialog(null, "Prazo de depreciação já foi ultrapassado.");
                return null;
            }
            if (meses > 0) {
                valorCalculado = percentualDepreciacao.divide(new BigDecimal(12), MathContext.DECIMAL64)
                        .divide(new BigDecimal(100))
                        .multiply(tfValorVenal.getValue(), MathContext.DECIMAL64)
                        .multiply(new BigDecimal(meses));
            }
            if (valorCalculado.doubleValue() >= tfValorVenal.getValue().doubleValue()) {
                JOptionPane.showMessageDialog(null, "Bem totalmente depreciado.");
                return tfValorVenal.getValue().doubleValue();
            }
        }
        return valorCalculado.doubleValue();
    }

    @Override
    public Double calcular16Hrs() {
        bem = jsBem.getValue();
        BigDecimal percentualDepreciacao = tfDepreciacao.getValue();
        BigDecimal valorCalculado = BigDecimal.ZERO;
        if (bem != null) {
            int meses = getMeses(bem.getAquisicao(), new DateTime(dtAquisicao.getDate()));
            int anos = getAnos(bem.getAquisicao(), new DateTime(dtAquisicao.getDate()));
            double prazo = getPrazoDepreciacao(bem.getGrupo());
            if (bem.getTipo() == Bem.Tipo.USADO) {
                prazo /= 2;
            }
            if (anos > prazo) {
                JOptionPane.showMessageDialog(null, "Prazo de depreciação já foi ultrapassado.");
                return null;
            }
            if (meses > 0) {
                BigDecimal acrescimo = percentualDepreciacao.divide(new BigDecimal(2));
                valorCalculado = percentualDepreciacao
                        .add(acrescimo)
                        .divide(new BigDecimal(12), MathContext.DECIMAL64)
                        .divide(new BigDecimal(100))
                        .multiply(tfValorVenal.getValue(), MathContext.DECIMAL64)
                        .multiply(new BigDecimal(meses));
            }
            if (valorCalculado.doubleValue() >= tfValorVenal.getValue().doubleValue()) {
                JOptionPane.showMessageDialog(null, "Bem totalmente depreciado.");
                return tfValorVenal.getValue().doubleValue();
            }
        }
        return valorCalculado.doubleValue();
    }

    @Override
    public Double calcular24Hrs() {
        bem = jsBem.getValue();
        BigDecimal percentualDepreciacao = tfDepreciacao.getValue();
        BigDecimal valorCalculado = BigDecimal.ZERO;
        if (bem != null) {
            int meses = getMeses(bem.getAquisicao(), new DateTime(dtAquisicao.getDate()));
            int anos = getAnos(bem.getAquisicao(), new DateTime(dtAquisicao.getDate()));
            double prazo = getPrazoDepreciacao(bem.getGrupo());
            if (bem.getTipo() == Bem.Tipo.USADO) {
                prazo /= 2;
            }
            if (anos > prazo) {
                JOptionPane.showMessageDialog(null, "Prazo de depreciação já foi ultrapassado.");
                return null;
            }
            if (meses > 0) {
                valorCalculado = percentualDepreciacao.multiply(new BigDecimal(2))
                        .divide(new BigDecimal(12), MathContext.DECIMAL64)
                        .divide(new BigDecimal(100), MathContext.DECIMAL64)
                        .multiply(tfValorVenal.getValue(), MathContext.DECIMAL64)
                        .multiply(new BigDecimal(meses));
            }
            if (valorCalculado.doubleValue() >= tfValorVenal.getValue().doubleValue()) {
                JOptionPane.showMessageDialog(null, "Bem totalmente depreciado.");
                return tfValorVenal.getValue().doubleValue();
            }
        }
        return valorCalculado.doubleValue();
    }

    @Override
    public Integer getMeses(Date date, DateTime now) {
        DateTime meses = new DateTime(date);
        Months m = Months.monthsBetween(meses, now);
        return m.getMonths();
    }

    @Override
    public Integer getAnos(Date data, DateTime now) {
        DateTime anos = new DateTime(data);
        Years y = Years.yearsBetween(anos, now);
        return y.getYears();
    }
}
