/**
 * Copyright (c) 1998-2011 Zap Informática, Inc. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Zap
 * Informática, Inc. ("Confidential Information"). You shall not disclose 
 * such Confidential Information and shall use it only in accordance with 
 * the terms of the license agreement you entered into with Zap Informática.
 */

package br.com.eswiv.tela.principal;

import br.com.eswiv.modelo.Usuario;
import br.com.eswiv.tela.cadastro.FBem;
import br.com.eswiv.tela.cadastro.FCidade;
import br.com.eswiv.tela.cadastro.FUsuarios;
import br.com.util.Util;
import com.zap.arca.LoggerEx;
import com.zap.arca.util.WindowUtils;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 * @version    1.00, 20 Dezembro 2010
 * @author     Edidelson
 * @since      V1  
 */
public class FPrincipal extends javax.swing.JFrame {

    Util util = new Util();
    private BufferedImage image;    
    Usuario usuario;

    // Bloco de inicialização que aplica o ícone da aplicação
    {
        util.inserirIconeAplicacao(this);
    }

    {
        try {
            image = ImageIO.read(getClass().getResourceAsStream("/resources/imagens/fundo-hd.png"));
        } catch (IOException ex) {
            LoggerEx.log(ex);
        }
    }

    /** Creates new form Principal */
    public FPrincipal(Usuario usuario) {
        WindowUtils.setSystemLookAndFeel();
        initComponents();
        setTitle("Projeto de ESWIV"); 
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        imPanel.setImage(image);
        iniciar();
        this.usuario = usuario;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgButtonPrincipal = new javax.swing.ButtonGroup();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        imPanel = new org.jdesktop.swingx.JXImagePanel();
        lbLicenciadoPara = new javax.swing.JLabel();
        tbAtalhos = new javax.swing.JToolBar();
        btSair = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbUsuarioLogado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDataAtual = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miBackup = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnMovimentos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("framePrincipal"); // NOI18N

        imPanel.setDefaultImage(null);

        lbLicenciadoPara.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        tbAtalhos.setBackground(new java.awt.Color(213, 220, 226));
        tbAtalhos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tbAtalhos.setFloatable(false);
        tbAtalhos.setRollover(true);

        btSair.setBackground(new java.awt.Color(213, 220, 226));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/lockstart_session.png"))); // NOI18N
        btSair.setToolTipText("Sair...");
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        tbAtalhos.add(btSair);

        javax.swing.GroupLayout imPanelLayout = new javax.swing.GroupLayout(imPanel);
        imPanel.setLayout(imPanelLayout);
        imPanelLayout.setHorizontalGroup(
            imPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbAtalhos, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLicenciadoPara, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        imPanelLayout.setVerticalGroup(
            imPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imPanelLayout.createSequentialGroup()
                .addComponent(tbAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(lbLicenciadoPara, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Usuário:");

        lbUsuarioLogado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbUsuarioLogado.setText("Administrador");

        jLabel4.setText("Data:");

        lbDataAtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDataAtual.setText("jLabel5");

        mnArquivo.setMnemonic('A');
        mnArquivo.setText("Arquivo");

        miBackup.setText("Backup...");
        miBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBackupActionPerformed(evt);
            }
        });
        mnArquivo.add(miBackup);
        mnArquivo.add(jSeparator1);

        miSair.setText("Sair...");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miSair);

        mbPrincipal.add(mnArquivo);

        jMenu1.setText("Cadastro");

        jMenuItem1.setText("Cadastro de usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cadastro de proprietário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mbPrincipal.add(jMenu1);

        mnMovimentos.setMnemonic('M');
        mnMovimentos.setText("Movimentos");
        mbPrincipal.add(mnMovimentos);

        jMenu2.setText("Ajuda");
        mbPrincipal.add(jMenu2);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator20, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(583, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(imPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataAtual)
                    .addComponent(lbUsuarioLogado)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_miSairActionPerformed

    private void miBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBackupActionPerformed
        new FBackup().setVisible(true); 
    }//GEN-LAST:event_miBackupActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
    this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new FCidade().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new FBem().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgButtonPrincipal;
    private javax.swing.JButton btSair;
    private org.jdesktop.swingx.JXImagePanel imPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JLabel lbDataAtual;
    private javax.swing.JLabel lbLicenciadoPara;
    private javax.swing.JLabel lbUsuarioLogado;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miBackup;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnMovimentos;
    private javax.swing.JToolBar tbAtalhos;
    // End of variables declaration//GEN-END:variables

    public void iniciar() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        lbDataAtual.setText(df.format(new java.util.Date()));
        if (usuario!=null)
        lbUsuarioLogado.setText(usuario.getApelido());
    }
}
