/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eswiv.tela.cadastro;

import br.com.eswiv.auxiliares.DSelecionarObjeto;
import br.com.eswiv.dao.DAOBem;
import br.com.eswiv.dao.DAOProprietario;
import br.com.eswiv.modelo.Bem;
import br.com.eswiv.modelo.Despesas;
import br.com.eswiv.modelo.IModelo;
import br.com.eswiv.modelo.Proprietario;
import br.com.eswiv.tela.generico.FrameGenerico;
import br.com.eswiv.tela.principal.DSobreSistema;
import br.com.eswiv.tela.tablemodel.BemTableModel;
import br.com.eswiv.tela.tablemodel.DespesaTableModel;
import br.com.eswiv.tela.tablemodel.ProprietarioTableModel;
import com.zap.arca.JASelectPicker;
import com.zap.arca.LoggerEx;
import com.zap.arca.document.NumberValueDocument;
import com.zap.arca.util.WindowUtils;
import java.awt.Component;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Edidelson
 */
public class FBem extends FrameGenerico {

    private Bem bem;
    private BemTableModel bemTableModel = new BemTableModel();
    private DespesaTableModel despesaTableModel = new DespesaTableModel();
    private Despesas despesa;
    private List<Despesas> despesas = new ArrayList<>();

    public FBem() {
        initComponents();
        setLocationRelativeTo(null);
        iniciar();
        actionMenu(INCLUSAO);
        util.setEnterButton(btOK);
        dtAquisicao.setDate(new java.util.Date());
        tfDepreciacao.setValue(getPercentual());
    }

    @Override
    public boolean verificarCampos(Component[] components) {

        Double valorDepreciacao = tfDepreciacao.getValue().doubleValue();
        if (valorDepreciacao > 100) {
            JOptionPane.showMessageDialog(null, "Percentual de depreciação inválido, valor maior que 100%");
            tfDepreciacao.requestFocus();
            return false;
        }
        if (cbGrupoBens.getSelectedIndex() == 4 && cbTurno.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Deve ser atribuido um turno para Máquinas e Equipamentos");
            cbTurno.requestFocus();
            return false;
        }
        if (!super.verificarCampos(components)) {
            return false;
        }
        return true;
    }

    @Override
    public void limparCampos() {
        despesaTableModel.clear();
        limpar();
        super.limparCampos();
        exibirDados(dao, tbBem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        tbIncluir = new javax.swing.JToggleButton();
        tbAlterar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btExcluir = new javax.swing.JToggleButton();
        btPesquisar = new javax.swing.JToggleButton();
        btFiltro = new javax.swing.JToggleButton();
        splitPaneCampos = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBem = new com.zap.arca.JATable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plCampos = new javax.swing.JPanel();
        lbGrupoBens = new javax.swing.JLabel();
        cbGrupoBens = new javax.swing.JComboBox();
        lbValorVenal = new javax.swing.JLabel();
        lbProprietario = new javax.swing.JLabel();
        jsProprietario = new com.zap.arca.JASelectPicker<Proprietario>();
        lbDataAquisicao = new javax.swing.JLabel();
        dtAquisicao = new com.zap.arca.JADatePicker();
        lnTurno = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox();
        lbDescricaoBens = new javax.swing.JLabel();
        tfDescricaoBens = new com.zap.arca.JATextField(80);
        tfCodigo = new com.zap.arca.JATextField(10,0);
        lbCodigo = new javax.swing.JLabel();
        lbProprietarioSelecionado = new javax.swing.JLabel();
        tfValorVenal = new com.zap.arca.JANumberFormatField();
        rbNovo = new javax.swing.JRadioButton();
        rbUsado = new javax.swing.JRadioButton();
        lbDepreciacao = new javax.swing.JLabel();
        tfDepreciacao = new com.zap.arca.JANumberFormatField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbDespesas = new com.zap.arca.JATable();
        dtDespesa = new com.zap.arca.JADatePicker();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        tfDescricaoDespesas = new com.zap.arca.JATextField(120);
        lbDescricao = new javax.swing.JLabel();
        lbValorDespesas = new javax.swing.JLabel();
        lbDataDespesas = new javax.swing.JLabel();
        tfValorDespesa = new com.zap.arca.JANumberFormatField();
        jButton2 = new javax.swing.JButton();
        btOK = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnIncluir1 = new javax.swing.JMenuItem();
        mnAlterar1 = new javax.swing.JMenuItem();
        mnExcluir1 = new javax.swing.JMenuItem();
        mnLimpar1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAtualizar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnFiltrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Bens e Despesas");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonGroup1.add(tbIncluir);
        tbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/add.png"))); // NOI18N
        tbIncluir.setToolTipText("Incluir");
        tbIncluir.setFocusable(false);
        tbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(tbIncluir);

        buttonGroup1.add(tbAlterar);
        tbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/edit.png"))); // NOI18N
        tbAlterar.setToolTipText("Alterar");
        tbAlterar.setFocusable(false);
        tbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbAlterar);
        jToolBar1.add(jSeparator1);

        buttonGroup1.add(btExcluir);
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/delete.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btExcluir);

        buttonGroup1.add(btPesquisar);
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(btPesquisar);

        buttonGroup1.add(btFiltro);
        btFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/filter.png"))); // NOI18N
        btFiltro.setToolTipText("Filtrar");
        btFiltro.setFocusable(false);
        btFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFiltro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltroActionPerformed(evt);
            }
        });
        jToolBar1.add(btFiltro);

        splitPaneCampos.setDividerLocation(120);
        splitPaneCampos.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tbBem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbBem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBem);
        tbBem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                alterar(tbBem);
            }
        });

        splitPaneCampos.setTopComponent(jScrollPane1);
        splitPaneCampos.setLeftComponent(jScrollPane1);

        plCampos.setBackground(new java.awt.Color(255, 255, 255));
        plCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbGrupoBens.setText("Grupo de Bens:");

        cbGrupoBens.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGrupoBensItemStateChanged(evt);
            }
        });
        cbGrupoBens.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbGrupoBensFocusLost(evt);
            }
        });

        lbValorVenal.setText("Valor Venal:");

        lbProprietario.setText("Proprietário:");

        jsProprietario.setLabel(lbProprietarioSelecionado);
        jsProprietario.setName("Proprietário"); // NOI18N
        jsProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsProprietarioActionPerformed(evt);
            }
        });
        jsProprietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jsProprietarioFocusLost(evt);
            }
        });

        lbDataAquisicao.setText("Data de Aquisição:");

        dtAquisicao.setName("Data de Aquisição"); // NOI18N

        lnTurno.setText("Turno:");

        lbDescricaoBens.setText("Descrição:");

        tfDescricaoBens.setName("Descrição"); // NOI18N

        tfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFocusLost(evt);
            }
        });

        lbCodigo.setText("Código:");

        tfValorVenal.setName("Valor Venal"); // NOI18N

        rbNovo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbNovo);
        rbNovo.setSelected(true);
        rbNovo.setText("Novo");

        rbUsado.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbUsado);
        rbUsado.setText("Usado");

        lbDepreciacao.setText("Depreciação:");

        tfDepreciacao.setName("Depreciação"); // NOI18N

        jLabel2.setText("%");

        javax.swing.GroupLayout plCamposLayout = new javax.swing.GroupLayout(plCampos);
        plCampos.setLayout(plCamposLayout);
        plCamposLayout.setHorizontalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescricaoBens))
                        .addGap(23, 23, 23)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addComponent(tfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(183, 183, 183)
                                .addComponent(lbDataAquisicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfDescricaoBens, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValorVenal)
                            .addComponent(lnTurno)
                            .addComponent(lbProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addComponent(jsProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbProprietarioSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbTurno, 0, 91, Short.MAX_VALUE)
                                    .addComponent(tfValorVenal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(plCamposLayout.createSequentialGroup()
                                        .addComponent(lbGrupoBens, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbGrupoBens, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(plCamposLayout.createSequentialGroup()
                                        .addComponent(rbNovo)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbUsado)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDepreciacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDepreciacao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        plCamposLayout.setVerticalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dtAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDataAquisicao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescricaoBens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescricaoBens))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProprietarioSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jsProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbProprietario)))
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbValorVenal))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValorVenal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGrupoBens, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGrupoBens)
                            .addComponent(lbDepreciacao)
                            .addComponent(tfDepreciacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbNovo)
                        .addComponent(rbUsado))
                    .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lnTurno)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jsProprietario.setDocument(new NumberValueDocument(10));
        tfCodigo.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
            public void changedUpdate(DocumentEvent e) { }
            public void removeUpdate(DocumentEvent e) {
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
        });

        jTabbedPane1.addTab("Bens", plCampos);
        plCampos.getAccessibleContext().setAccessibleName("Informações dos Bens");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbDespesas);
        tbDespesas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {

                if(!e.getValueIsAdjusting()) {

                    alterar(tbDespesas);
                }
            }
        });

        dtDespesa.setName("Data"); // NOI18N

        btAdicionar.setText("Adicionar");
        btAdicionar.setOpaque(false);
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setOpaque(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.setOpaque(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        tfDescricaoDespesas.setName("Descrição"); // NOI18N

        lbDescricao.setText("Descrição:");

        lbValorDespesas.setText("Valor:");

        lbDataDespesas.setText("Data:");

        tfValorDespesa.setName("Valor"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValorDespesas)
                            .addComponent(lbDataDespesas)
                            .addComponent(lbDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfDescricaoDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfValorDespesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtDespesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 458, Short.MAX_VALUE)
                                .addComponent(btAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRemover))
                            .addComponent(jScrollPane6))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescricaoDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorDespesas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataDespesas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btAlterar)
                    .addComponent(btRemover))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Despesas", jPanel1);

        jButton2.setText("Cancelar");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btOK, jButton2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOK)
                    .addComponent(jButton2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        splitPaneCampos.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(splitPaneCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(splitPaneCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Editar");

        mnIncluir1.setText("Incluir");
        mnIncluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIncluir1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnIncluir1);

        mnAlterar1.setText("Alterar");
        mnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterar1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnAlterar1);

        mnExcluir1.setText("Excluir");
        mnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExcluir1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnExcluir1);

        mnLimpar1.setText("Limpar");
        mnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLimpar1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnLimpar1);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Exibir");

        mnAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnAtualizar.setText("Atualizar");
        mnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarActionPerformed(evt);
            }
        });
        jMenu3.add(mnAtualizar);
        jMenu3.add(jSeparator2);

        mnFiltrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnFiltrar.setText("Filtrar...");
        mnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFiltrarActionPerformed(evt);
            }
        });
        jMenu3.add(mnFiltrar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenu4.add(jSeparator3);

        mnSobre.setText("Sobre...");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu4.add(mnSobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIncluirActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_tbIncluirActionPerformed

    private void tbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAlterarActionPerformed
        actionMenu(ALTERACAO);
    }//GEN-LAST:event_tbAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        actionMenu(PESQUISAR);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltroActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_btFiltroActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_mnAtualizarActionPerformed

    private void mnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFiltrarActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_mnFiltrarActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        new DSobreSistema(this, true).setVisible(true);
    }//GEN-LAST:event_mnSobreActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        if (verificarCampos(camposVerificar)) {
            // Adiciona ou altera o objeto
            inserirOuAlterar();
            limparCampos();
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (despesa != null) {
            if (verificarCampos()) {
                despesa.setDescricao(tfDescricaoDespesas.getText());
                despesa.setDataDespesa(dtDespesa.getDate());
                despesa.setValor(tfValorDespesa.getValue().doubleValue());
                exibirDados(despesas, tbDespesas);
                limpar();
            }
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        if (verificarCampos()) {
            despesa = new Despesas();
            despesa.setDescricao(tfDescricaoDespesas.getText());
            despesa.setDataDespesa(dtDespesa.getDate());
            despesa.setValor(tfValorDespesa.getValue().doubleValue());
            despesas.add(despesa);
            exibirDados(despesas, tbDespesas);
            limpar();
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        despesas.remove(despesa);
        exibirDados(despesas, tbDespesas);
    }//GEN-LAST:event_btRemoverActionPerformed

    private void jsProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsProprietarioActionPerformed
        if (JASelectPicker.SELECT_KEY.equals(evt.getActionCommand())) {
            jsProprietario.requestFocus();
            new DSelecionarObjeto(this, true, jsProprietario)
                    .title("Selecionar Cidade...")
                    .dao(DAOProprietario.class)
                    .model(new ProprietarioTableModel())
                    .frame(FProprietario.class).open();
        }
    }//GEN-LAST:event_jsProprietarioActionPerformed

    private void jsProprietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jsProprietarioFocusLost
        if (jsProprietario.getText().equals("")) {
            lbProprietarioSelecionado.setText("");
            jsProprietario.setValue(null, "");
            return;
        }
        DAOProprietario daoCidade = new DAOProprietario();
        String value = jsProprietario.getEditor().getText();
        Proprietario c = null;
        if (value.length() > 0) {
            c = daoCidade.consultar(Integer.valueOf(value), false);
        }
        jsProprietario.setValue(c, c != null ? c.getCodigo() : "");
    }//GEN-LAST:event_jsProprietarioFocusLost

    private void mnIncluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIncluir1ActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_mnIncluir1ActionPerformed

    private void mnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterar1ActionPerformed
        actionMenu(ALTERACAO);
    }//GEN-LAST:event_mnAlterar1ActionPerformed

    private void mnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExcluir1ActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_mnExcluir1ActionPerformed

    private void mnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLimpar1ActionPerformed
        actionMenu(LIMPAR);
    }//GEN-LAST:event_mnLimpar1ActionPerformed

    private void cbGrupoBensFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbGrupoBensFocusLost
    }//GEN-LAST:event_cbGrupoBensFocusLost

    private void cbGrupoBensItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGrupoBensItemStateChanged
        tfDepreciacao.setValue(getPercentual());
    }//GEN-LAST:event_cbGrupoBensItemStateChanged

    private void tfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusLost
        consultar();
    }//GEN-LAST:event_tfCodigoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JToggleButton btExcluir;
    private javax.swing.JToggleButton btFiltro;
    private javax.swing.JButton btOK;
    private javax.swing.JToggleButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbGrupoBens;
    private javax.swing.JComboBox cbTurno;
    private com.zap.arca.JADatePicker dtAquisicao;
    private com.zap.arca.JADatePicker dtDespesa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private com.zap.arca.JASelectPicker<Proprietario> jsProprietario;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDataAquisicao;
    private javax.swing.JLabel lbDataDespesas;
    private javax.swing.JLabel lbDepreciacao;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDescricaoBens;
    private javax.swing.JLabel lbGrupoBens;
    private javax.swing.JLabel lbProprietario;
    private javax.swing.JLabel lbProprietarioSelecionado;
    private javax.swing.JLabel lbValorDespesas;
    private javax.swing.JLabel lbValorVenal;
    private javax.swing.JLabel lnTurno;
    private javax.swing.JMenuItem mnAlterar1;
    private javax.swing.JMenuItem mnAtualizar;
    private javax.swing.JMenuItem mnExcluir1;
    private javax.swing.JMenuItem mnFiltrar;
    private javax.swing.JMenuItem mnIncluir1;
    private javax.swing.JMenuItem mnLimpar1;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JPanel plCampos;
    private javax.swing.JRadioButton rbNovo;
    private javax.swing.JRadioButton rbUsado;
    private javax.swing.JSplitPane splitPaneCampos;
    private javax.swing.JToggleButton tbAlterar;
    private com.zap.arca.JATable tbBem;
    private com.zap.arca.JATable tbDespesas;
    private javax.swing.JToggleButton tbIncluir;
    private com.zap.arca.JATextField tfCodigo;
    private com.zap.arca.JANumberFormatField tfDepreciacao;
    private com.zap.arca.JATextField tfDescricaoBens;
    private com.zap.arca.JATextField tfDescricaoDespesas;
    private com.zap.arca.JANumberFormatField tfValorDespesa;
    private com.zap.arca.JANumberFormatField tfValorVenal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciar() {
        dao = new DAOBem();

        tbPrincipal = tbBem;
        toggleButton = tbIncluir;
        ctChave = tfCodigo;

        tbBem.setName("TB_FBEM");
        tbBem.setModel(bemTableModel);
        tbDespesas.setName("TB_FDESPESAS");
        tbDespesas.setModel(despesaTableModel);


        camposVerificar = new Component[]{tfValorVenal, tfDepreciacao, dtAquisicao, jsProprietario};
        camposLimpar = new Component[]{tfDescricaoBens, tfCodigo, tfDepreciacao, jsProprietario, tfValorVenal, dtAquisicao,
            dtDespesa, tfValorDespesa, jsProprietario, lbProprietarioSelecionado};

        //carrega o combo de turno
        cbTurno.addItem(null);
        for (Bem.Turno turno : Bem.Turno.values()) {
            cbTurno.addItem(turno.getDescricao());
        }
        for (Bem.Categorias categorias : Bem.Categorias.values()) {
            cbGrupoBens.addItem(categorias.getDescricao());
        }

        WindowUtils.nextEnter(plCampos);
        WindowUtils.exitEsc(this);
        configurarSincronizacao(dao, tbBem);

    }

    public Bem.Turno getTurno() {
        if (cbTurno.getSelectedIndex() == 1) {
            return Bem.Turno.H8;
        } else if (cbTurno.getSelectedIndex() == 2) {
            return Bem.Turno.H16;
        } else if (cbTurno.getSelectedIndex() == 3) {
            return Bem.Turno.H24;
        } else {
            return null;
        }
    }

    public void setTurno(Bem.Turno turno) {
        switch (turno) {
            case H8:
                cbTurno.setSelectedIndex(1);
                break;
            case H16:
                cbTurno.setSelectedIndex(2);
                break;
            case H24:
                cbTurno.setSelectedIndex(3);
                break;
        }
    }

    public Bem.Tipo getTipo() {
        if (rbNovo.isSelected()) {
            return Bem.Tipo.NOVO;
        } else {
            return Bem.Tipo.USADO;
        }
    }

    public void setTipo(Bem.Tipo tipo) {
        switch (tipo) {
            case NOVO:
                rbNovo.setSelected(true);
                break;
            case USADO:
                rbUsado.setSelected(true);
                break;
        }
    }

    public void setCategoria(Bem.Categorias categorias) {
        switch (categorias) {
            case E:
                cbGrupoBens.setSelectedIndex(0);
                break;
            case I:
                cbGrupoBens.setSelectedIndex(1);
                break;
            case MU:
                cbGrupoBens.setSelectedIndex(2);
                break;
            case V:
                cbGrupoBens.setSelectedIndex(3);
                break;
            case ME:
                cbGrupoBens.setSelectedIndex(4);
                break;
        }
    }

    public Bem.Categorias getCategoria() {
        if (cbGrupoBens.getSelectedIndex() == 0) {
            return Bem.Categorias.E;
        } else if (cbGrupoBens.getSelectedIndex() == 1) {
            return Bem.Categorias.I;
        } else if (cbGrupoBens.getSelectedIndex() == 2) {
            return Bem.Categorias.MU;
        } else if (cbGrupoBens.getSelectedIndex() == 3) {
            return Bem.Categorias.V;
        } else {
            return Bem.Categorias.ME;
        }
    }

    @Override
    public void inserirOuAlterar() {
        bem = new Bem();
        bem.setAquisicao(dtAquisicao.getDate());
        bem.setDescricao(tfDescricaoBens.getText());
        bem.setGrupo(getCategoria());
        bem.setProprietario(jsProprietario.getValue());
        bem.setValorVenal(tfValorVenal.getValue().doubleValue());
        bem.setDepreciacao(tfDepreciacao.getValue().doubleValue());
        bem.setTurno(getTurno());
        bem.setTipo(getTipo());
        for (Despesas d : despesaTableModel.getData()) {
            d.setBem(bem);
        }
        bem.setDespesas(despesaTableModel.getData());
        try {
            if (tbAlterar.isSelected()) {
                bem.setCodigo(Integer.valueOf(tfCodigo.getText()));
                dao.alterar(bem);
            } else {
                dao.adicionar(bem);
            }
        } catch (RuntimeException ex) {
            LoggerEx.log(ex);
        }
    }

    @Override
    public void preencherCampos(IModelo m) {
        if (m instanceof Bem) {
            bem = (Bem) m;
            tfCodigo.setText(String.valueOf(bem.getCodigo()));
            tfDescricaoBens.setText(bem.getDescricao());
            cbGrupoBens.setSelectedItem(bem.getGrupo());
            dtAquisicao.setDate(bem.getAquisicao());
            tfValorVenal.setValue(bem.getValorVenal().doubleValue());
            Proprietario proprietario = bem.getProprietario();
            jsProprietario.setValue(proprietario, proprietario != null ? proprietario.getCodigo() : "");
            setCategoria(bem.getGrupo());
            setTipo(bem.getTipo());
            if (bem.getTurno() != null) {
                setTurno(bem.getTurno());
            } else {
                cbTurno.setSelectedIndex(0);
            }
            tfDepreciacao.setValue(bem.getDepreciacao().doubleValue());
            despesas.clear();
            for (Despesas d : bem.getDespesas()) {
                despesas.add((Despesas) d.clone());
            }

            exibirDados(despesas, tbDespesas);
        }
        if (m instanceof Despesas) {
            despesa = (Despesas) m;
            tfDescricaoDespesas.setText(despesa.getDescricao());
            tfValorDespesa.setValue(despesa.getValor().doubleValue());
            dtDespesa.setDate(despesa.getDataDespesa());
        }

    }

    @Override
    public void preencherTabela(int linha, IModelo i) {
    }

    public void limpar() {
        tfDescricaoDespesas.setText("");
        tfValorDespesa.setValue(BigDecimal.ZERO);
        dtDespesa.setDate(null);
        despesa = null;
    }

    public boolean verificarCampos() {
        if (tfDescricaoDespesas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo obrigatório não preenchido");
            tfDescricaoDespesas.requestFocus();
            return false;
        }
        if (tfValorDespesa.getValue().equals(BigDecimal.ZERO)) {
            JOptionPane.showMessageDialog(null, "Campo obrigatório não preenchido");
            tfValorDespesa.requestFocus();
            return false;
        }
        if (dtDespesa.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Campo obrigatório não preenchido");
            dtDespesa.requestFocus();
            return false;
        }
        return true;
    }

    public double getPercentual() {
        if (cbGrupoBens.getSelectedIndex() == 0) {
            return Bem.Categorias.E.getTaxaPercentual();
        } else if (cbGrupoBens.getSelectedIndex() == 1) {
            return Bem.Categorias.I.getTaxaPercentual();
        } else if (cbGrupoBens.getSelectedIndex() == 2) {
            return Bem.Categorias.MU.getTaxaPercentual();
        } else if (cbGrupoBens.getSelectedIndex() == 3) {
            return Bem.Categorias.V.getTaxaPercentual();
        } else {
            return Bem.Categorias.ME.getTaxaPercentual();
        }
    }

    private boolean consultar() throws NumberFormatException, HeadlessException {
        if (tfCodigo.getText().equals("")) {
            return true;
        }
        boolean encontrou = false;
        loop:
        for (int i = 0; i < bemTableModel.getRowCount(); i++) {
            int linha = Integer.valueOf(tfCodigo.getText());
            if (bemTableModel.getRow(i).getCodigo().equals(linha)) {
                tbBem.changeSelection(i, 0, false, false);
                encontrou = true;
                break loop;
            }
        }
        if (!encontrou) {
            JOptionPane.showMessageDialog(null, "Código Inválido");
            limparCampos();
            tfDepreciacao.requestFocus();
        }
        return false;
    }
}
