/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eswiv.tela.cadastro;

import br.com.eswiv.dao.DAOCategoria;
import br.com.eswiv.modelo.Categoria;
import br.com.eswiv.modelo.IModelo;
import br.com.eswiv.tela.generico.FrameGenerico;
import br.com.eswiv.tela.principal.DSobreSistema;
import br.com.eswiv.tela.tablemodel.CategoriaTableModel;
import com.zap.arca.LoggerEx;
import com.zap.arca.util.WindowUtils;
import java.awt.Component;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Edidelson
 */
public class FCategoria extends FrameGenerico {

    /**
     * Creates new form FCidade
     */
    private Categoria categoria;
    private CategoriaTableModel categoriaTableModel = new CategoriaTableModel();

    public FCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        iniciar();
        actionMenu(INCLUSAO);
        util.setEnterButton(btOK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategoria = new com.zap.arca.JATable();
        jScrollPane2 = new javax.swing.JScrollPane();
        plCampos = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plCamposCategoria = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfCodigo = new com.zap.arca.JATextField(6,0);
        tfDescricao = new com.zap.arca.JATextField();
        jButton2 = new javax.swing.JButton();
        btOK = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        tbIncluir = new javax.swing.JToggleButton();
        tbAlterar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btExcluir = new javax.swing.JToggleButton();
        btPesquisar = new javax.swing.JToggleButton();
        btFiltro = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnIncluir = new javax.swing.JMenuItem();
        mnAlterar = new javax.swing.JMenuItem();
        mnExcluir = new javax.swing.JMenuItem();
        mnLimpar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAtualizar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnFiltrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miAjudaConteudo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cidades");

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tbCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCategoria);
        tbCategoria.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                alterar(tbCategoria);
            }
        });

        jSplitPane1.setTopComponent(jScrollPane1);

        plCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        plCamposCategoria.setBackground(new java.awt.Color(255, 255, 255));
        plCamposCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbCodigo.setText("Código:");

        lbNome.setText("Descrição:");

        tfDescricao.setName("Descrição"); // NOI18N

        javax.swing.GroupLayout plCamposCategoriaLayout = new javax.swing.GroupLayout(plCamposCategoria);
        plCamposCategoria.setLayout(plCamposCategoriaLayout);
        plCamposCategoriaLayout.setHorizontalGroup(
            plCamposCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        plCamposCategoriaLayout.setVerticalGroup(
            plCamposCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        tfCodigo.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                // verificaAlteracao();
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
            public void changedUpdate(DocumentEvent e) { }
            public void removeUpdate(DocumentEvent e) {
                //verificaAlteracao();
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
        });

        jTabbedPane1.addTab("Categoria", plCamposCategoria);

        jButton2.setText("Cancelar");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plCamposLayout = new javax.swing.GroupLayout(plCampos);
        plCampos.setLayout(plCamposLayout);
        plCamposLayout.setHorizontalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addComponent(btOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        plCamposLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btOK, jButton2});

        plCamposLayout.setVerticalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOK)
                    .addComponent(jButton2))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(plCampos);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonGroup1.add(tbIncluir);
        tbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/add.png"))); // NOI18N
        tbIncluir.setToolTipText("Incluir");
        tbIncluir.setFocusable(false);
        tbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(tbIncluir);

        buttonGroup1.add(tbAlterar);
        tbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/edit.png"))); // NOI18N
        tbAlterar.setToolTipText("Alterar");
        tbAlterar.setFocusable(false);
        tbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbAlterar);
        jToolBar1.add(jSeparator1);

        buttonGroup1.add(btExcluir);
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/delete.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btExcluir);

        buttonGroup1.add(btPesquisar);
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(btPesquisar);

        buttonGroup1.add(btFiltro);
        btFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/filter.png"))); // NOI18N
        btFiltro.setToolTipText("Filtrar");
        btFiltro.setFocusable(false);
        btFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFiltro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltroActionPerformed(evt);
            }
        });
        jToolBar1.add(btFiltro);

        jMenu1.setText("Arquivo");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        mnIncluir.setText("Incluir");
        mnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIncluirActionPerformed(evt);
            }
        });
        jMenu2.add(mnIncluir);

        mnAlterar.setText("Alterar");
        mnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarActionPerformed(evt);
            }
        });
        jMenu2.add(mnAlterar);

        mnExcluir.setText("Excluir");
        mnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExcluirActionPerformed(evt);
            }
        });
        jMenu2.add(mnExcluir);

        mnLimpar.setText("Limpar");
        mnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLimparActionPerformed(evt);
            }
        });
        jMenu2.add(mnLimpar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exibir");

        mnAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnAtualizar.setText("Atualizar");
        mnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarActionPerformed(evt);
            }
        });
        jMenu3.add(mnAtualizar);
        jMenu3.add(jSeparator2);

        mnFiltrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnFiltrar.setText("Filtrar...");
        mnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFiltrarActionPerformed(evt);
            }
        });
        jMenu3.add(mnFiltrar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        miAjudaConteudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miAjudaConteudo.setText("Conteúdo de Ajuda");
        jMenu4.add(miAjudaConteudo);
        jMenu4.add(jSeparator3);

        mnSobre.setText("Sobre...");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu4.add(mnSobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIncluirActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_tbIncluirActionPerformed

    private void tbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAlterarActionPerformed
        actionMenu(ALTERACAO);
    }//GEN-LAST:event_tbAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        actionMenu(PESQUISAR);
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltroActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_btFiltroActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIncluirActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_mnIncluirActionPerformed

    private void mnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarActionPerformed
        actionMenu(ALTERACAO);
    }//GEN-LAST:event_mnAlterarActionPerformed

    private void mnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExcluirActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_mnExcluirActionPerformed

    private void mnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLimparActionPerformed
        actionMenu(LIMPAR);
    }//GEN-LAST:event_mnLimparActionPerformed

    private void mnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarActionPerformed
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_mnAtualizarActionPerformed

    private void mnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFiltrarActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_mnFiltrarActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        new DSobreSistema(this, true).setVisible(true);
    }//GEN-LAST:event_mnSobreActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        // Verifica se os campos foram preenchidos
        if (verificarCampos(camposVerificar)) {
            // Adiciona ou altera o objeto
            inserirOuAlterar();
            limparCampos();
        }
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_btOKActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCategoria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btExcluir;
    private javax.swing.JToggleButton btFiltro;
    private javax.swing.JButton btOK;
    private javax.swing.JToggleButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JMenuItem miAjudaConteudo;
    private javax.swing.JMenuItem mnAlterar;
    private javax.swing.JMenuItem mnAtualizar;
    private javax.swing.JMenuItem mnExcluir;
    private javax.swing.JMenuItem mnFiltrar;
    private javax.swing.JMenuItem mnIncluir;
    private javax.swing.JMenuItem mnLimpar;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JPanel plCampos;
    private javax.swing.JPanel plCamposCategoria;
    private javax.swing.JToggleButton tbAlterar;
    private com.zap.arca.JATable tbCategoria;
    private javax.swing.JToggleButton tbIncluir;
    private com.zap.arca.JATextField tfCodigo;
    private com.zap.arca.JATextField tfDescricao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciar() {
        dao = new DAOCategoria();

        tbPrincipal = tbCategoria;
        toggleButton = tbIncluir;
        ctChave = tfCodigo;

        tbCategoria.setName("TB_FCATEGORIA");
        tbCategoria.setModel(categoriaTableModel);

        camposVerificar = new Component[]{tfDescricao};
        camposLimpar = new Component[]{tfDescricao, tfCodigo};

        WindowUtils.nextEnter(plCamposCategoria);
        WindowUtils.exitEsc(this);
        configurarSincronizacao(dao, tbCategoria);
    }

    @Override
    public void inserirOuAlterar() {
        categoria = new Categoria();
        categoria.setDescricao(tfDescricao.getText());
        try {
            if (tbAlterar.isSelected()) {
                categoria.setCodigo(Integer.valueOf(tfCodigo.getText()));
                dao.alterar(categoria);
            } else {
                dao.adicionar(categoria);
            }
        } catch (RuntimeException ex) {
            LoggerEx.log(ex);
        }
    }

    @Override
    public void preencherCampos(IModelo m) {
        categoria = (Categoria) m;
        tfCodigo.setText(String.valueOf(categoria.getCodigo()));
        tfDescricao.setText(categoria.getDescricao());
    }

    @Override
    public void preencherTabela(int linha, IModelo i) {
    }
}
