/*
 * DFiltrar.java
 *
 * Created on 26/12/2010, 21:33:51
 */

package br.com.eswiv.auxiliares;

import br.com.eswiv.tela.generico.DialogGenerico;
import br.com.eswiv.tela.generico.FrameGenerico;
import com.zap.arca.JATable;
import br.com.util.Util;
import com.zap.arca.util.WindowUtils;
import javax.swing.DefaultComboBoxModel;
import table.model.filter.TableFilter;

/**
 *
 * @author Everton
 */
public class DFiltro extends DialogGenerico {

    Util util = new Util();
    JATable table;
    String[] campos;
    FrameGenerico frame;

    // Bloco de inicialização que aplica o ícone da aplicação
    {
        WindowUtils.exitEsc(this);
    }

    /**
     * Inicia o componente e configura as variáveis de instancia
     * @param parent JFrame que implementa IFuncionalidades
     * @param modal
     * @param table Tabela que será filtrada
     * @param campos campos que aparecerão para seleção
     */
    
    public DFiltro(FrameGenerico parent, boolean modal, JATable table, String[] campos) {
        super(parent, modal);
        frame = parent;
        this.table = table;
        this.campos = campos;
        initComponents();
        WindowUtils.nextEnter(plCampos);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plCampos = new javax.swing.JPanel();
        dCbCampo = new javax.swing.JComboBox();
        dLbCampo = new javax.swing.JLabel();
        dTfFiltrar = new javax.swing.JTextField();
        dLbFiltrar = new javax.swing.JLabel();
        painelButton = new javax.swing.JPanel();
        dBtCancelar = new javax.swing.JButton();
        dBtOk = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro");

        dCbCampo.setModel(new DefaultComboBoxModel(campos));
        dCbCampo.setSelectedIndex(1);

        dLbCampo.setText("Campo:");

        dLbFiltrar.setText("Filtrar:");

        javax.swing.GroupLayout plCamposLayout = new javax.swing.GroupLayout(plCampos);
        plCampos.setLayout(plCamposLayout);
        plCamposLayout.setHorizontalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dLbCampo)
                    .addComponent(dLbFiltrar))
                .addGap(18, 18, 18)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dCbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTfFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        plCamposLayout.setVerticalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLbCampo)
                    .addComponent(dCbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLbFiltrar)
                    .addComponent(dTfFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dBtCancelar.setText("Cancelar");
        dBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBtCancelarActionPerformed(evt);
            }
        });

        dBtOk.setText("Ok");
        dBtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBtOkActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelButtonLayout = new javax.swing.GroupLayout(painelButton);
        painelButton.setLayout(painelButtonLayout);
        painelButtonLayout.setHorizontalGroup(
            painelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelButtonLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(dBtOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dBtCancelar)
                .addContainerGap())
        );

        painelButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btLimpar, dBtCancelar, dBtOk});

        painelButtonLayout.setVerticalGroup(
            painelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelButtonLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(painelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBtCancelar)
                    .addComponent(btLimpar)
                    .addComponent(dBtOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dBtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtOkActionPerformed
        //if(!dTfFiltrar.getText().equals("")) {
            TableFilter.filter(dTfFiltrar, table, dCbCampo.getSelectedIndex());
        //} else {
        //    frame.exibirDados(frame.dao, table, frame.camposTabela, frame.classesTabela, frame.tamanhosTabela);
        //}
        this.dispose();
    }//GEN-LAST:event_dBtOkActionPerformed

    private void dBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtCancelarActionPerformed
        /**
        dTfFiltrar.setText("");
        dCbCampo.setSelectedIndex(1);
        frame.exibirDados(frame.dao, table, frame.camposTabela, frame.classesTabela, frame.tamanhosTabela);
         * 
         */
        this.dispose();
    }//GEN-LAST:event_dBtCancelarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton dBtCancelar;
    private javax.swing.JButton dBtOk;
    private javax.swing.JComboBox dCbCampo;
    private javax.swing.JLabel dLbCampo;
    private javax.swing.JLabel dLbFiltrar;
    private javax.swing.JTextField dTfFiltrar;
    private javax.swing.JPanel painelButton;
    private javax.swing.JPanel plCampos;
    // End of variables declaration//GEN-END:variables

    public void limpar() {
        dTfFiltrar.setText("");
        dCbCampo.setSelectedIndex(1);
        TableFilter.filter(dTfFiltrar, table, dCbCampo.getSelectedIndex());
        //frame.exibirDados(frame.dao, table, frame.camposTabela, frame.classesTabela, frame.tamanhosTabela);
        table.changeSelection(0, 0, false, false);
        this.dispose();
    }
}
